#!/bin/sh
# Script for assignment 5 part 2
# Author: Tiago Neto

if [ "$1" = "start" ]
then
    echo "Starting aesdsocket"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    
elif [ "$1" = "stop" ]
then
    echo "Stopping aesdsocket"
    # Send SIGTERM to aesdsocket process
    start-stop-daemon -K -n aesdsocket
else
    echo "Usage: $0 {start|stop}"
    exit 1
fi